[workspace]
name = "Ribasim-Delwaq"
channels = ["conda-forge"]
platforms = ["win-64"]

[dependencies]
imod = "*"
ipykernel = "*"
mypy = "*"
netcdf4 = "*"
pip = "*"
ribasim = "==2025.6.0"
ruff = "*"
pydantic = ">=2"
pydantic-settings = "*"
pytest = "*"
python = "3.13.*"
xugrid = "*"


[pypi-dependencies]
ribasim_tools = { path = "src/ribasim_tools", editable = true }
