[project]
name = "Ribasim-Delwaq"
channels = ["conda-forge"]
platforms = ["win-64"]

[dependencies]
ipykernel = "*"
mypy = "*"
netcdf4 = "*"
pip = "*"
pytest = ">=9.0.1,<10"
ribasim = "==2025.5.0"
ruff = "*"
pydantic = ">=2"
pydantic-settings = "*"
python = "3.13.*"
xugrid = "*"


[pypi-dependencies]
ribasim_tools = { path = "src/ribasim_tools", editable = true }
